Create basic general styles and variables
PDCMFinder/cancer-models pull request #21
Opened 2022-12-01 13:09 UTC by mriios

## Issue
Fixes #20 

## Description
Create scss files for variables, mixins, types, and define such styles.

## Testing instructions
`yarn dev` and view styles on index page

## Screenshots (optional)
<img width="930" alt="image" src="https://user-images.githubusercontent.com/25350391/205060880-7608679e-cfed-4727-ba85-2f69fa304783.png">

2022-12-01 19:09 UTC, ficolo requested changes
Change version of `@next/font` and `next` to match.

2022-12-01 19:09 UTC, ficolo commented on package.json
> +    "@next/font": "^13.0.5",
Had problems running the code with this version of "`@next/font`". Got a warning about the different version of `@next/font` and `next`:

<img width="883" alt="Screenshot 2022-12-01 at 19 05 01" src="https://user-images.githubusercontent.com/2343039/205138249-6494fbd7-9451-4ad4-b237-13a398037a87.png">

And the app failed to load in the browser:

![Screenshot 2022-12-01 at 19 03 57](https://user-images.githubusercontent.com/2343039/205138135-ce361bec-0b05-4175-b1e5-8145d5c37743.png)

After upgrading to `"next": "13.0.5"` it worked just fine.

2022-12-05 19:24 UTC, mriios commented
@ficolo could you see if you still get the error? I never got it so I can't really test that part

2022-12-05 20:38 UTC, ficolo approved these changes

2022-12-06 08:36 UTC, merged