Create Index page
PDCMFinder/cancer-models pull request #38
Opened 2023-01-03 17:47 UTC by mriios

## Issue
Fixes #37 

## Description
Create index/home page for website, based on graphic proposal

## Testing instructions
`yarn dev` then go to `http://localhost:3000/`

## Screenshots (optional)
<img width="1512" alt="Screenshot 2023-01-03 at 17 47 26" src="https://user-images.githubusercontent.com/25350391/210412600-40504eac-eaeb-4f4a-927e-221fa10b1abe.png">

2023-01-03 17:56 UTC, mriios commented
sorry for no commits on this one ): forgot to make them every so often

2023-01-05 09:36 UTC, mriios commented
Last commit fixes #39

2023-01-05 09:54 UTC, ficolo commented on package.json
> +		"sb": "start-sotorybook -p 6006",
typo

2023-01-05 10:02 UTC, ficolo requested changes
Some small changes in tow files requested. Minor code style things.

2023-01-05 15:19 UTC, mriios commented on src/components/FeedbackSection/FeedbackSection.tsx
> +	let backgroundColorClass;
noted! Will take it into consideration for next time

2023-01-05 15:26 UTC, ficolo approved these changes

2023-01-05 15:26 UTC, ficolo commented
Looks great!

2023-01-05 16:47 UTC, merged